### ISSUE TITLE
treaty_of_tarbagatay is blocked

### ISSUE THREAD

**Issue by Lopatouovalil** [Benisman1488/Anon-s-Historical-Bloat-Mod#12]
treaty_of_tarbagatay is blocked because it demands province with id 1068 to be owned by QNG(or by his subject) but that province is annexed by convention_of_peking (if QNC agree it will gives you all your cores as RUS so it gives you cores from  colonize_uriankhai decision too) when colonize_uriankhai is already taken.

**Comment by Benisman1488** [comment]
Solved in 4/20/21, thanks for the input.
