### ISSUE TITLE
Taking the "Unify Georgia" decision as Kartli-Kakheti does nothing even if you satisfy all the requirements

### ISSUE THREAD

**Issue by JohnnyBarbouny** [Benisman1488/Anon-s-Historical-Bloat-Mod#15]
As said in the title. I unified Georgia but when I click the decision nothing happens. It should be fixed

**Comment by JohnnyBarbouny** [comment]
The "Form Transcaucasia" decision seemingly does nothing for Greater Georgia/Sakartvelo

**Comment by Benisman1488** [comment]
solved all in 4/20/21
