### ISSUE TITLE
Broken Russian Descisions

### ISSUE THREAD

**Issue by Sploofd** [Benisman1488/Anon-s-Historical-Bloat-Mod#2]
The Russian expansion into Central Asia and china is busted. The first decision to take land from China either, if they accept, leaves a random chunk of Kyrgyzstan under Chinese rule,  or if they decline, completely breaks. The second Russian decision to expand in to China can often not be completed as you are only allowed to do it if Xinjiang owns the land, meaning if the rebellion succeeds, and China annexes Xinjiang it wont work. The two conflicting systems for the great game also means you'll be  accidentally breaking truces, leading to huge loss of prestige. There is no decision for annexing Alaska, which although isn't a bug, its still annoying as it leaves border gore.. The decision for buying Madagascar from the French leaves a bunch a random Madagascar tiles still under French rule. I also seem to never be able to take Manchuria,  from the Qing, with it only letting me acquire nanjing or beijang. On an unrelated note, sometimes,when the Austrians release Vojvodina, they never annex it, adding more bordergore.  I love the mod btw, its very fun

**Comment by Sploofd** [comment]
I've been playing some more and noticed another problem, that Russia's population is completely fucked(at the end of my play through, with moderate expansion( Afghanistan and Galicia, parts of northern china, and annexing all my puppets ) my population was about 180 million (900 million total), about 6 times the actual population of the Soviet union at the time) because of the Donbass decisions, leading to me being able to field 3000 brigades, and having single tiles with over 20 millions pops, leading to a massive (we are talking millions) of unemployed factory workers ( despite having maxed out number of factories, all at very high (40-80)levels)and loads of soldiers (I could recruit 800 brigades from the single tile) and also fucking my demographics, as most of these tile are majority Cossack or Ukrainian, making the once beautiful demographics map look disgusting as  there are yellow and light blue Ukrainian and Cossack enclaves everywhere(at the end of the game my population was 30% Russian, 22% Ukrainian, and 15% Cossack with the starting pops being  45% Russian, 20% Ukrainian, and a measly 4% Cossack). It also leads to a completely OP industry, my industry at the end of the game being 1800, with me barley investing in industry, and i surpassed the UK in 1865.

**Comment by Sploofd** [comment]
Im bored enough to start making some actual edits; so far ive added a bunch of provinces to the us east coast for some future Alaskan and Japanese flavour. Sadly I am too retarded to know how GitHub works so it will probably be a while till i know how to put stuff on this. Happy to help with anything if you want to

**Comment by Sploofd** [comment]
Aight found some new problems. Most of the russian north america decisions didnt work as they neede both alaska_sale_refused and fort_ross_sale_refused, but it is impossible to get alaska_sale_refused if you had fort_ross_sale_refused. Fixed it now. Also added some decisions to expand fort ross

**Comment by Sploofd** [comment]
Also fixed madagascar, you didnt update the decision with the new provinces

**Comment by Benisman1488** [comment]
Tried solving most of the issues you've listed, couldn't really catch what you meant for these two:
>I also seem to never be able to take Manchuria, from the Qing, with it only letting me acquire nanjing or beijang.
>The two conflicting systems for the great game also means you'll be accidentally breaking truces, leading to huge loss of prestige.
Care to elaborate? Thanks.

If you're on Dick's discord, contact me. That's where most of the brainstorming for the mod is discussed.

**Comment by Sploofd** [comment]
For the Manchuria thing, I'm not sure why, but when I justify a take state cassus belli when the Qing do own the border inner Manchuria regions, they never pop up as a war goal. For the Great Game, the decisions to go to war with a country do not have a at truce condition with that country, so if you are not careful, you accidentally break a whole bunch of truces.

**Comment by Benisman1488** [comment]
Alright, I fixed the Great Game stuff, hopefully. As for the Manchuria conquest, you can't take states from any of the countries belonging to the East Asian culture group (Japan, Korea, China) just like that, HPM/HFM disabled it ages ago because people used it to cheese the game as Westernized Nations. In order to take states from them you need to check out the requirements, it's in the cb_types.txt file, in demand_concession_casus_belli, under allowed_states.

Also I'm not posting the discord's address here, I don't have permission for that. Gonna have to find that on your own.

**Comment by Sploofd** [comment]
OK thanks!
