### ISSUE TITLE
Irish retains the "Londonderry" to "Derry" decision after renaming it to gaelic names and can't rename it back after taking such decision

### ISSUE THREAD

**Issue by JohnnyBarbouny** [Benisman1488/Anon-s-Historical-Bloat-Mod#3]
It's confusing, I know.

**Comment by Sploofd** [comment]
You know you can write these all in one issue post using replies right?

**Comment by Benisman1488** [comment]
It's alright, I'll place them all here and close/delete the other issues. Just make sure to put all future issues in a single thread, don't wanna make a mess of the issues board.

**Comment by Benisman1488** [comment]
>Those are the Cornish names.
>Plymouth = Aberplymm
>Exeter = Karesk

>EXTRA: Welsh names for Cornwall

>Exeter = Caerwysg
>Plymouth = Aberplym

**Comment by Benisman1488** [comment]
>Considering of Ireland is called "Eire" ((And should be Éire)) When fascist, it would be more aesthetic if the other nations followed such example

>Scotland = Alba
>Wales = Cymru
>Cornwall = Kernow
>Ireland = Éire
>Isle of Man = Ellan Vannin (Or "Mannin")
>Brittanny: Breizh

**Comment by Benisman1488** [comment]
>Italian name for Annecy:
>Annecy = Ennèsia

**Comment by Benisman1488** [comment]
>Brittany Celtic names:
>Brest = Bryste
>Saint-Brieuc = Sant-Brieg
>Vannes = Gwened
>Rennes = Roazhon
>Nantes = Naoned

>Channel Islands = Inizi angl-ha-norman (Or "Inizi Mor Breizh")

**Comment by JohnnyBarbouny** [comment]
Sorry, I am used to making multiple issues in more popular mods like Kaiserreich.

I wanted to update the Channel Islands britannic name. A fascist/neo celtic Brittany would call the Channel Islands "Inizi Mor Breizh" (Literally "Islands of the Breton sea")

The English Channel is called "Mor Breizh" in their language, literally "Breton Sea", so "Inizi Mor Breizh" would be a better choice.
The "Enstablish Neo-celticism" decision works for Britanny, but it removes English from accepted cultures rather than French.

**Comment by JohnnyBarbouny** [comment]
I've also made a suggestion where England should remove Celtic cultures from the accepted cultures to enstablish Anglo supremacy

**Comment by JohnnyBarbouny** [comment]
The "Organize the Algerian Departments" decision for France doesn't work because it says that Algeria doesn't exist even if it does!

**Comment by JohnnyBarbouny** [comment]
St. Johns, In Newfoundland, is wrongly renamed to "Quèbec"

**Comment by JohnnyBarbouny** [comment]
In British Colombia, after France takes over the Region, "Victoria" should be renamed to "Napoléon"

Newfoundland, even if held by the British, gets its provinces renamed in French even if France doesn't own the provinces

**Comment by JohnnyBarbouny** [comment]
When you pick the "Unite the Guyanas" decision, you release Guyana but without the Barima and Pirara provinces!

**Comment by JohnnyBarbouny** [comment]
@Benisman1488 When you pick the french language schooling decision for France you get to assimilate Catalonia but not Wallonia, i think the decisions should overlook french cores for majority-franco areas nonetheless of lacking french cores

**Comment by JohnnyBarbouny** [comment]
@Benisman1488 The Derry issue makes AI Ireland always take the "Irish names" decision and then the "Londonderry to Derry" one, making Derry the only non-Irish name in Ireland.
Perhaps the Celtic names decision should only be locked behind a reactionary/fascist government and can be taken multiple times?

**Comment by Benisman1488** [comment]
Solved in 4/20/21, thanks for the input.
